# Generated by Django 5.2.5 on 2025-11-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villain',
            name='email_contato',
        ),
    ]
