# Generated by Django 5.2.5 on 2025-09-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.post'),
            preserve_default=False,
        ),
    ]
